### ISSUE TITLE
Scene crash backup system

### ISSUE THREAD

**Issue by kotcrab** [kotcrab/vis-editor#105]
Currently there is one scene backup system, backup is created before scene saving. So it is possible to restore scene if saving went wrong.
Since VisEditor is still in early versions crashes are often, better backup system is needed. 

Ideas:
- Do emergency save of all open scenes with unsaved changes on editor crash. After restarting editor a dialog should be shown that will provide option for simple restore.
- History: built-in history module which would backup scene after every save (or every X saves, or every X minutes)
- Auto saves: Auto save scene after X minutes. Before auto save dialog will be shown: "Auto save in 10 seconds" or something like that, so user can simply cancel it.

Thoughts, ideas? Calling people who may have something to say: @StQuote @intrigus @omomthings

**Comment by omomthings** [comment]
you said it all.. obviously auto save enable/disable and timer should be settable from the options.. otherwise those improvements should be enough!

**Comment by StQuote** [comment]
It's a good idea to save scenes on editor crash. I think, would be correct to save scenes with changes, not all opened. 

Autosave is good point too. And I'm agree with @omomthings . In case when viseditor project files store in Dropbox or Google Drive is critically needed to have option to enable/disable autosaving . I never use autosavings, so from user point view for me it's hard to say something about showing dialog before make autosave.

I do not understood about History module. What is difference with Autosaves?

**Comment by omomthings** [comment]
@StQuote think about history as an archive system, @kotcrab this makes me think of something, history should be made over X saves not X minutes since there should be auto save system to take care of that, also an important think is that it should make a trace after X user saves , not autosaves, or there will be a quick overload of archives, Also I think that since there will be auto save, user (at least me) wont make manual saves, therefor I think that the last auto save before closing the editor should be considered as a user save (from the perspective of the history module), like this the history system would be effective even if you completly rely on the auto save system (obviously if the user make a manual save no need to convert anything)

**Comment by kotcrab** [comment]
Of course auto save and auto save time will be configurable from options.

@omomthings 
I also wonder how deep history should be to not overload it. Maybe storing only what changed is good idea and only periodically save full file.

If you try to quit editor with unsaved changes it displays "Unsaved resources" dialog where user can either save or discard changes so it would count as standard user save.

@StQuote 
History would be something like built-in version control. There will be separate dialog allowing to browse and rollback scene file to any previous version and autosave is just system that will trigger saves periodically.

>It's a good idea to save scenes on editor crash. I think, would be correct to save scenes with changes, not all opened. 

You are right, I changed it.
