### ISSUE TITLE
VisUI: VisDialog does not close

### ISSUE THREAD

**Issue by mbrlabs** [kotcrab/vis-editor#188]
Hello,
i found a bug: the VisDialog does not close when hitting the close button for the second time. The first time works.

I attached a little example (txt, because github doesn't let me post java files...)
Just open & close the dialog 2 times. The second time it can't be closed.

Seems to be introduced in VisUI 1.1.0, 1.0.0 worked. 
I'm using libGDX 1.9.3, running on Linux Mint.

[DialogTester.java.txt](https://github.com/kotcrab/vis-editor/files/301395/DialogTester.java.txt)

**Comment by kotcrab** [comment]
Thanks for reporting and providing actually runnable example. I fixed it but since you are reusing dialog this would suggest that you are using it for something complex. It's better to use `VisWindow` directly for complex dialogs. `VisDialog` comes from scene2d.ui and in my opinion isn't useful for anything complicated and its API is kinda bad. I'm actually thinking about removing it in some major new version.

**Comment by mbrlabs** [comment]
Yes, i'm using this for all kinds of complex dialogs. Alright, then i'm going to switch to VisWindow.
Thanks for the quick fix!

**Comment by kotcrab** [comment]
No problem. I won't remove it anytime soon though, it's more like VisUI 2.0 thing so there is no need to hurry.
