### ISSUE TITLE
VisUI: FileChooser hangs while building initial list

### ISSUE THREAD

**Issue by WickedShell** [kotcrab/vis-editor#201]
With the commit to support loading the directory contents in a different thread fixed a large number of responsiveness issues, when the chooser is first shown, and the last used location contains a large number of files (or is slow to enumerate to the OS due to networking problems) the GL thread is hung until the results are returned.

Ideally the show should use the same deferred onto a different thread approach as the later listing.

Encountered on 1.1.5-SNAPSHOT

**Comment by WickedShell** [comment]
Was supposed to be on 1.1.5-SNAPSHOT but was on 1.1.4 by accident, give me a bit to confirm that this is still happening in 1.1.5 (I suspect it is, but I should confirm that first)

**Comment by kotcrab** [comment]
I don't think this is caused by listing files, even the initial list is performed on separate thread. Is it reproducible every time you create it where last directly contained large number of files? If so you can use profiler (e.g. visualvm, bundled with JDK) to check what is actually taking that much time. In my case there is no difference if last directory was with small or large number of files and most time during creation takes loading preferences by lwjgl3:
![2016-07-27_0829](https://cloud.githubusercontent.com/assets/4594081/17166102/3fc19f58-53d5-11e6-8083-2b261d2a86a1.png)

**Comment by WickedShell** [comment]
Closing as can't reproduce, (even though I had encountered it twice when I posted the issue). If it happens again I will try and find some more helpful information.
