### ISSUE TITLE
There is no way to listen for menu widgets open/close events

### ISSUE THREAD

**Issue by metaphore** [kotcrab/vis-editor#209]
When you work with menu, sometimes you have dynamic content in there (generic name for menu item or enable/disabled state should be updated). This usually happens when user opens menu and it should be updated somehow. I'm thinking of simple listeners for that kind of event. Like `MenuBar` could notify that current `Menu` is changed inside `MenuBar#setCurrentMenu(Menu)` and it always means that menu was opened. It would be great to have something similar for composite menu items (that have sub items).

What do you think?

**Comment by kotcrab** [comment]
Notice that `(Popup)Menu` is an Actor, you can use this to get notified when it's added or removed from stage:
```java
		Menu fileMenu = new Menu("File") {
			@Override
			protected void setStage (Stage stage) {
				super.setStage(stage);
				if (stage != null) {
					System.out.println("Shown");
				} else {
					System.out.println("Hidden");
				}
			}
		};
```

This can be also applied to sub menus since they are just `PopupMenu`. However menu structure shouldn't be changed after it's appeared on screen because menus sizes are used to calculate menu and submenus positions. That means updating before showing. So in case of standalone `PopupMenu` - you need to show it manually so it's easy, just update before showing. That's actually done in some places in VisUI and VisEditor. In case of `MenuBar` I could add an option to set menu open event listener. I don't want to make users override `setCurrentMenu(Menu)` since VisUI uses listener approach for events. Does that sound ok?

**Comment by metaphore** [comment]
My general goal is to bring notification actions to LML, but without listeners it's not possible. Even with my local menu widgets inheritence, I can't access those important methods. Listener in  `setCurrentMenu(Menu)` would be very useful, thanks!

**Comment by kotcrab** [comment]
MenuBar now supports listening for close/open events,

**Comment by metaphore** [comment]
Just awesome, thanks!
