### ISSUE TITLE
vis-runtime.gwt.xml not available in runtime version 0.3.4-sources or even in version 0.3.3-sources

### ISSUE THREAD

**Issue by itsabhiaryan** [kotcrab/vis-editor#224]
I am trying to deploy my project on web but due to unavailability of gwt.xml, I am not able to provide source path in GdxDefinition.gwt.xml.

**Comment by kotcrab** [comment]
GWT support was dropped in 0.3.3.

**Comment by itsabhiaryan** [comment]
Please tell me reason, why you dropped GWT support.

**Comment by kotcrab** [comment]
It's too much hassle to support, with its long build times and requirement for separate `runtime-gwt` project just because runtime level annotations aren't fully supported. And don't forget the need to update `gwt.xml`, need to have no-arg constructors for serialized objects and so on, I'm pretty sure it wasn't working below 0.3.3 anyways. Maybe we will have TeaVM based web backend soon.

**Comment by itsabhiaryan** [comment]
Thanks for explanation.
