### ISSUE TITLE
VisEditor runtime library for libgdx

### ISSUE THREAD

**Issue by dmitrypotenko** [kotcrab/vis-editor#246]
Hi!
I have recently started to use VisEditor runtime library for libgdx, and i've faced problem. I can only add systems to artemis WorldConfiguration by your API due to "locked" build process of EntityEngineConfiguration class. Subsequently, i can't add custom FieldHandler to WorldConfiguration. Could you please increase flexibility of configuration process of EntityEngineConfiguration class?

**Comment by kotcrab** [comment]
Funny because that locking is needed because Artemis itself is locking configuration and doesn't allow getting added systems. 

We can have listener in `EntityEngineConfiguration` that will be called after constructing `WorldConfiguration`, listener will get instance of `WorldConfiguration` . Or we can just expose needed methods directly in `EntityEngineConfiguration`. Fell free to send pr for this.
