### ISSUE TITLE
Access to file chooser's text field

### ISSUE THREAD

**Issue by metaphore** [kotcrab/vis-editor#260]
In save mode, I have a file name to suggest to a user, but it appears like I have no any way to do this. `FileChooser.setSelectedFiles(FileHandle...)` does provide option to select specific file programmatically, but it depends on displayed file views and drops files that are not visible right now. I guess it wouldn't be a big deal to simply provide setter for the file name text field. What do you say?

**Comment by kotcrab** [comment]
I can't provide direct access to it because after adding to stage, file chooser refreshes itself which only preserves actual selected files and not field text. 

I added a method that let's you set default file name which will be used when chooser is added to stage and no other files was already selected.

**Comment by metaphore** [comment]
Yep, this should solve the case. Thanks!
