### ISSUE TITLE
Are there plans to separate VisUI from VisEditor?

### ISSUE THREAD

**Issue by jdiazcano** [kotcrab/vis-editor#299]
Right now it is pretty hard to contribute to the project as it is inside VisEditor so doing tests locally (or even a submodule) is far from ideal.

Are there plans to separate the two projects?

If not, would it be ok for me to do it?

**Comment by kotcrab** [comment]
See https://github.com/kotcrab/vis-editor/issues/261

After opening this project in IDE you will only get `ui` and `usl` modules loaded. VisEditor modules are not loaded and recognized by the IDE. VisEditor is set to use fixed version of VisUI so even breaking changes to `ui` module won't affect VisEditor. If you are working on VisUI you can pretty much ignore the rest of the code.

Splitting repository is problematic, I'm not seeing good way to do it. I guess if that ever happened then this repository would have to become `vis-ui` to keep stars and follows. Editor code would be moved to new repository.

> If not, would it be ok for me to do it?

No, PR of this size would not be accepted and doesn't even seem feasible because it would require to create separate repository.

**Comment by jdiazcano** [comment]
Thanks for the explanation but if the only thing that is stopping this to be separated is because is problematic then there should be no problem.

Basically what I see right now is two products in the same repository (and one of them with two modules) so for me this is pretty confusing. This is even clearer when you say that VisEditor uses a fixed version of VisUI, that, for me, is a clear separation (even more if iirc, VisEditor is not maintained anymore) hence having them in the same repository will be confusing for future contributors (me included).

I think that the best approach, as you said, is for this repository to become VisUI and a separate one to become VisEditor.

As for the `Would it be ok for me to do it?` I mostly meant to have a fork with just the VisUI project which is the one I am mostly interested on

**Comment by kotcrab** [comment]
I agree, it is pretty confusing. Maybe I'm the one being stubborn here... Okay, I've decided to split it. Though it probably won't happen until next week. See #300 for tracking. I think we can close this.

> As for the Would it be ok for me to do it? I mostly meant to have a fork with just the VisUI project which is the one I am mostly interested on

Well, there is nothing in the license that can stop you from doing this.

**Comment by jdiazcano** [comment]
Waiting some time is definitely not a problem!

**Comment by kotcrab** [comment]
@jdiazcano done, let me know if you spot some issues with wrong links or invalid information etc.
